version: '2'
services:
  db:
    image: mysql:8
    ports:
        - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
